#spring.application.name=crud
## =====================================================================
## Database Connection Properties
## =====================================================================
## The JDBC URL format: jdbc:postgresql://<host>:<port>/<database_name>
#spring.datasource.url=jdbc:postgresql://localhost:5432/crud-db
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## =====================================================================
## JPA / Hibernate Configurations
## =====================================================================
## Configures the SQL dialect for PostgreSQL
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
## Controls database DDL generation (update, create, create-drop, validate, none)
#spring.jpa.hibernate.ddl-auto=update
#
## Enable logging of SQL statements to the console
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#server.address=0.0.0.0
#server.port=8080


spring.application.name=crud

# =====================================================================
# Database Connection Properties
# =====================================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =====================================================================
# JPA / Hibernate Configurations
# =====================================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Enable logging of SQL statements to the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =====================================================================
# Server Configuration
# =====================================================================
server.port=${PORT:8080}